[package]
name = "future-rwlock"
version = "0.1.0"
authors = ["Marco Napetti <marco.napetti@gmail.com>"]
edition = "2018"

[dependencies]
future-parking_lot = { git = "https://github.com/nappa85/future-parking_lot.git" }
