[package]
name = "future-rwlock"
version = "0.1.0"
authors = ["Marco Napetti <marco.napetti@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.1"
parking_lot = "0.8"

[dev-dependencies]
lazy_static = "1.3"
